aeskvlapivs/aeskvlapivs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from consultorio.urls import consultorio_patterns





urlpatterns = [
    path('', include('core.urls')),
    path('pacientes/', include(consultorio_patterns)),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

aeskvlapivs/consultorio/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import (PacienteListView, PacienteDetailView, PacienteCreate, PacienteUpdate, 
PacienteDeleteView, SearchResultsView, SearchReevResultsView, ReevaluacionListView, ReevalucionDetailView, 
ReevaluacionUpdate, ReevaluacionCreate, ReevalucionDeleteView,UrgenciasListView, UrgenciasCreate, UrgenciasDetailView,
UrgenciasUpdate, UrgenciasDeleteView, SearchUrgenciasResultsView,
)


app_name = "consultorio"


consultorio_patterns = ([
    path('', PacienteListView.as_view(), name='pacientes'), 
    path('create/', PacienteCreate.as_view(),name='nuevo_paciente'),
    path('<int:pk>/<slug:paciente_slug>/', PacienteDetailView.as_view(), name='paciente'),
    path('update/<int:pk>/', PacienteUpdate.as_view(),name='actualizar_paciente'),
    path('delete/<int:pk>/', PacienteDeleteView.as_view(),name='eliminar paciente'),
    path("search/", SearchResultsView.as_view(), name="search_results"),
    path("upload_pac", views.uploadFilePac, name = "uploadFile_pac"),     
    
    path('reevaluaciones/', ReevaluacionListView.as_view(), name='reevaluaciones'),
    path('create_reev/', ReevaluacionCreate.as_view(),name='nueva_reevaluacion'),
    path('<int:pk>/', ReevalucionDetailView.as_view(), name='reevaluacion'),
    path('update_reevaluacion/<int:pk>/', ReevaluacionUpdate.as_view(),name='Actualizar_reevaluacion'),    
    path('delete_reev/<int:pk>/', ReevalucionDeleteView.as_view(),name='eliminar reevaluacion'),
    path("search_reev/", SearchReevResultsView.as_view(), name="search_results_reev"),
    path("upload_reev", views.uploadFileReev, name = "uploadFile_reev"),

    path('urgencias/', UrgenciasListView.as_view(), name='pacientes_urgencias'),
    path('create_urgencias/', UrgenciasCreate.as_view(),name='nueva_urgencia'),
    path('<int:pk>/slugify', UrgenciasDetailView.as_view(), name='urgencias'),
    path('update_urgencias/<int:pk>/', UrgenciasUpdate.as_view(),name='actualizar_urgencia'),    
    path('delete_urgencias/<int:pk>/', UrgenciasDeleteView.as_view(),name='eliminar_urgencia'),
    path("search_urgencias/", SearchUrgenciasResultsView.as_view(), name="search_results_urgencias"),
    path("upload_urgencias", views.uploadFileUrgencias, name = "uploadFile_urgencias"),

   
], 'consultorio')

aeskvlapivs/core/urls.py
from django.urls import path
from . import views
from core.views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),   
    path('sample/', SamplePageView.as_view(), name='sample'),
   
   
]

aeskvlapivs/core/models.py
from django.db import models

# Create your models here.



aeskvlapivs/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView 

class HomePageView(TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Tittle'] = 'EASKVLAPIVS'
        return context

class SamplePageView(TemplateView):
    template_name = "core/sample.html"






'''def home(request):
    return render(request, "core/home.html")

def sample(request):
    return render(request, "core/sample.html")'''

aeskvlapivs/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
  </head>
  <body>
    <body>
      <!-- Navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">AESKVLAPIVS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'consultorio:pacientes' %}">Pacientes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'consultorio:pacientes_urgencias' %}">Urgencias</a>
              </li>
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/admin/">
                  {% if request.user.is_staff %}Admin{% else %}Acceder{% endif %}
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- Contenido -->
      {% block content %}{% endblock %}
      <!-- Javascript -->
      <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/main.js' %}"></script>
  </body>
</html>

aeskvlapivs/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">
  <div style="padding-top:50px; text-align:center;">
    <h1>{{Tittle}}</h1>
    <p class="lead">Nuestro Escritorio Médico</p>
    
    
  </div>
</div>

{% endblock %}

aeskvlapivs/core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'core/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}