aeskvlapivs/aeskvlapivs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from consultorio.urls import consultorio_patterns





urlpatterns = [
    path('', include('core.urls')),
    path('pacientes/', include(consultorio_patterns)),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

aeskvlapivs/consultorio/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import (PacienteListView, PacienteDetailView, PacienteCreate, PacienteUpdate, 
PacienteDeleteView, SearchResultsView, SearchReevResultsView, ReevaluacionListView, ReevalucionDetailView, 
ReevaluacionUpdate, ReevaluacionCreate, ReevalucionDeleteView,UrgenciasListView, UrgenciasCreate, UrgenciasDetailView,
UrgenciasUpdate, UrgenciasDeleteView, SearchUrgenciasResultsView,
)


app_name = "consultorio"


consultorio_patterns = ([
    path('', PacienteListView.as_view(), name='pacientes'), 
    path('create/', PacienteCreate.as_view(),name='nuevo_paciente'),
    path('<int:pk>/<slug:paciente_slug>/', PacienteDetailView.as_view(), name='paciente'),
    path('update/<int:pk>/', PacienteUpdate.as_view(),name='actualizar_paciente'),
    path('delete/<int:pk>/', PacienteDeleteView.as_view(),name='eliminar paciente'),
    path("search/", SearchResultsView.as_view(), name="search_results"),
    path("upload_pac", views.uploadFilePac, name = "uploadFile_pac"),     
    
    path('reevaluaciones/', ReevaluacionListView.as_view(), name='reevaluaciones'),
    path('create_reev/', ReevaluacionCreate.as_view(),name='nueva_reevaluacion'),
    path('<int:pk>/', ReevalucionDetailView.as_view(), name='reevaluacion'),
    path('update_reevaluacion/<int:pk>/', ReevaluacionUpdate.as_view(),name='Actualizar_reevaluacion'),    
    path('delete_reev/<int:pk>/', ReevalucionDeleteView.as_view(),name='eliminar reevaluacion'),
    path("search_reev/", SearchReevResultsView.as_view(), name="search_results_reev"),
    path("upload_reev", views.uploadFileReev, name = "uploadFile_reev"),

    path('urgencias/', UrgenciasListView.as_view(), name='pacientes_urgencias'),
    path('create_urgencias/', UrgenciasCreate.as_view(),name='nueva_urgencia'),
    path('<int:pk>/slugify', UrgenciasDetailView.as_view(), name='urgencias'),
    path('update_urgencias/<int:pk>/', UrgenciasUpdate.as_view(),name='actualizar_urgencia'),    
    path('delete_urgencias/<int:pk>/', UrgenciasDeleteView.as_view(),name='eliminar_urgencia'),
    path("search_urgencias/", SearchUrgenciasResultsView.as_view(), name="search_results_urgencias"),
    path("upload_urgencias", views.uploadFileUrgencias, name = "uploadFile_urgencias"),

   
], 'consultorio')

aeskvlapivs/core/urls.py
from django.urls import path
from . import views
from core.views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),   
    path('sample/', SamplePageView.as_view(), name='sample'),
   
   
]

aeskvlapivs/consultorio/forms.py
from logging import PlaceHolder
from django import forms
from .models import Paciente, Reevaluacion, Urgencias
from django import forms

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['name', 'gender', 'dob', 'nationality', 'etnia', 'scholarship', 'job',
     'religion', 'sport', 'civil_status', 'adress', 'email', 'phone', 'entitlement', 'specify',
     'insurance', 'immediate_background', 'smoking', 'alcohol', 'drugs_adictions', 'allergies',
     'dislipidemia', 'dm', 'hta', 'inf_ang_de_pecho', 'evc', 'ivp', 'EPOC', 'cancer', 'otras_enf',
     'cir_previas', 'obs', 'actual_situation', 'tension_sistolica', 'tension_diastolica', 'fc','fr',
     'temp', 'saturacion', 'dextrostix', 'a1c', 'peso', 'estatura', 'per_abdominal', 'Imagenología1',
     'Imagenología2', 'Imagenología3', 'Labs1', 'Labs2', 'recetas', 'diagnosis', 'obs', 'txs',
     'adendums', 

    ]
        
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}, ),
            
            'dob': forms.DateInput( attrs={'class':'form-control', 'placeholder':'dd/mm/aaaa'}),
            
            'nationality': forms.TextInput(attrs={'class':'form-control'}),
            'etnia': forms.TextInput(attrs={'class':'form-control'}),
            'scholarship': forms.TextInput(attrs={'class':'form-control'}),
            'job': forms.TextInput(attrs={'class':'form-control'}),
            'adress': forms.TextInput(attrs={'class':'form-control'}),
            'immediate_background': forms.Textarea(attrs={'class':'form-control'}),
            'obs': forms.Textarea(attrs={'class':'form-control'}),
            'cir_previas': forms.TextInput(attrs={'class':'form-control'}),
            'otras_enf': forms.Textarea(attrs={'class':'form-control'}),
            'actual_situation': forms.Textarea(attrs={'class':'form-control'}),
          
            'diagnosis': forms.Textarea(attrs={'class':'form-control'}),
            'txs': forms.Textarea(attrs={'class':'form-control'}),
            'adendums': forms.Textarea(attrs={'class':'form-control'}),
                        
        }


class ReevaluacionForm(forms.ModelForm):
    class Meta:
        model = Reevaluacion
        fields = ['paciente', 'age', 'dxs_previos', 'immediate_background',
        'tension_sistolica', 'tension_diastolica', 'fc', 'fr', 'temp', 'saturacion', 'dextrostix', 'a1c', 'peso', 'estatura',
        'per_abdominal', 'expl', 'Imagenología1', 'Imagenología2', 'Imagenología3', 'Labs1', 'Labs2',
        'recetas', 'diagnosis', 'obs', 'txs', 

    ]
        raw_id_fields = ('paciente', )
        autocomplete_fields = ('paciente',)
        widgets = {
            'immediate_background': forms.Textarea(attrs={'class':'form-control'}),
            'expl': forms.Textarea(attrs={'class':'form-control'}),
            'dxs_previos': forms.Textarea(attrs={'class':'form-control'}),
            'diagnosis': forms.Textarea(attrs={'class':'form-control'}),
            'obs': forms.Textarea(attrs={'class':'form-control'}),
            'txs': forms.Textarea(attrs={'class':'form-control'}),
            
                       
        }
        

class UrgenciasForm(forms.ModelForm):
    class Meta:
        model = Urgencias
        fields = ['nombre', 'edad', 'im_bkground', 'other_bkground', 'tension_sistolica', 'tension_diastolica', 'Diaforesis',
        'fc', 'fr', 'O2', 'saturacion', 'dextrostix', 'temp', 'peso', 'estatura', 'per_abdominal',
        'AVPU', 'apertura_ocular', 'Respuesta_Verbal', 'Respuesta_Motora', 'expl', 'dxs', 'MANEJO_INICIAL', ]

        raw_id_fields = ('nombre', )
        autocomplete_fields = ('nombre',)
        widgets = {
                   
            'im_bkground': forms.Textarea(attrs={'class':'form-control', 
            'placeholder':'Describa por qué llegó el paciente, quien lo trajo o como llegó, qué sucedió antes (se desmayó, tuvo un accidente. empezó a sentirse mal...), describa el habitus exterior y los síntomas que el paciente pueda referir'}),
            'other_bkground': forms.Textarea(attrs={'class':'form-control', 'placeholder' : 'Describa y recopile enfermedades previas, alergias y lo que considere importante'}),
            'expl': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Complemente el hábitus exterior y escriba lo relevante desde la cabeza a los pies'}),
            'dxs': forms.Textarea(attrs={'class':'form-control'}),
            'MANEJO_INICIAL': forms.Textarea(attrs={'class':'form-control'}),
            'immediate_background': forms.Textarea(attrs={'class':'form-control'}),
            'obs': forms.Textarea(attrs={'class':'form-control'}),
         
                        
        }

aeskvlapivs/consultorio/views.py
from unicodedata import name
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from . import models
from django.db.models import Q
from .models import Paciente, Urgencias
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from .models import Paciente, Reevaluacion
from .forms import PacienteForm, ReevaluacionForm, UrgenciasForm

class StaffRequiredMixin(object):
    """
    Este mixin requerirá que el usuario sea miembro del staff
    """
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StaffRequiredMixin, self).dispatch(request, *args, **kwargs)

def uploadFilePac(request):
    if request.method == "POST":
        # Fetching the form data
        fileTitle = request.POST["fileTitle"]
        uploadedFile = request.FILES["Imagenología1", 'Imagnología2', 'Imagenología3','Labs1', 
        'Labs2', 'Labs3']

        # Saving the information in the database
        document = models.Paciente(
            title = fileTitle,
            uploadedFile = uploadedFile
        )
        document.save()

    documents = models.Paciente.objects.all()

    return render(request, "consultorio/paciente_list.html", context = {
        "paciente": documents
    })


class SearchResultsView(ListView):
    model = Paciente
    template_name = 'search_results.html'

    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        object_list = Paciente.objects.filter(
            Q(name__icontains=query) | Q(phone__icontains=query)
        )
        return object_list

class PacienteListView(ListView):
    model = Paciente
    template_name = 'paciente_list.html'
    
    

class PacienteDetailView(DetailView):
    model = Paciente

    
@method_decorator(staff_member_required, name='dispatch')
class PacienteCreate(CreateView):
    model = Paciente
    form_class = PacienteForm
    success_url = reverse_lazy('consultorio:pacientes')


@method_decorator(staff_member_required, name='dispatch')
class PacienteUpdate(UpdateView):
    model = Paciente
    form_class = PacienteForm
    template_name_suffix = '_update_form'

    
    def get_success_url(self):
        return reverse_lazy('consultorio:actualizar_paciente', args=[self.object.id]) + '?ok'

@method_decorator(staff_member_required, name='dispatch')
class PacienteDeleteView(DeleteView):
    model = Paciente
    success_url = reverse_lazy('consultorio:pacientes')






# Create your views here.


#def pacientes(request):
 #   pacientes = get_list_or_404(Paciente)
  #  return render(request, 'consultorio/pacientes.html', {'pacientes':pacientes})

#def paciente(request, page_id, page_slug):
 #   paciente = get_object_or_404(Paciente, id=page_id)
  #  return render(request, 'consultorio/paciente.html', {'paciente':paciente})



#REEVALUACION


def uploadFileReev(request):
    if request.method == "POST":
        # Fetching the form data
        fileTitle = request.POST["fileTitle"]
        uploadedFile = request.FILES["Imagenología1", 'Imagnología2', 'Imagenología3','Labs1', 
        'Labs2', 'Labs3']

        # Saving the information in the database
        document = models.Reevaluacion(
            title = fileTitle,
            uploadedFile = uploadedFile
        )
        document.save()

    documents = models.Reevaluacion.objects.all()

    return render(request, "consultorio/reevaluacion_list.html", context = {
        "reevaluacion": documents
    })


class SearchReevResultsView(ListView):
    model = Reevaluacion
    template_name = 'searchreev_results.html'

    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        object_list = Reevaluacion.objects.filter(
            Q(paciente__name__icontains=query)
        )
        return object_list



class ReevaluacionListView(ListView):
    model = Reevaluacion
    template_name = 'reevaluacion_list.html'
    
    

class ReevalucionDetailView(DetailView):
    model = Reevaluacion


@method_decorator(staff_member_required, name='dispatch')
class ReevaluacionCreate(CreateView):
    model = Reevaluacion
    form_class = ReevaluacionForm
    success_url = reverse_lazy('consultorio:reevaluaciones')


@method_decorator(staff_member_required, name='dispatch')
class ReevaluacionUpdate(UpdateView):
    model = Reevaluacion
    form_class = ReevaluacionForm
    template_name_suffix = '_update_form'

    
    def get_success_url(self):
        return reverse_lazy('consultorio:Actualizar_reevaluacion', args=[self.object.id]) + '?ok'


@method_decorator(staff_member_required, name='dispatch')
class ReevalucionDeleteView(DeleteView):
    model = Reevaluacion
    success_url = reverse_lazy('consultorio:reevaluaciones')



#URGENCIAS

def uploadFileUrgencias(request):
    if request.method == "POST":
        # Fetching the form data
        fileTitle = request.POST["fileTitle"]
        uploadedFile = request.FILES["Imagenología1", 'Imagnología2', 'Imagenología3','Labs1', 
        'Labs2', 'Labs3']

        # Saving the information in the database
        document = models.Urgencias(
            title = fileTitle,
            uploadedFile = uploadedFile
        )
        document.save()

    documents = models.Urgencias.objects.all()

    return render(request, "consultorio/urgencias_list.html", context = {
        "urgencias": documents
    })


class SearchUrgenciasResultsView(ListView):
    model = Urgencias
    template_name = 'searchurg_results.html'

    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        object_list = Urgencias.objects.filter(
            Q(nombre__name__icontains=query)
        )
        return object_list



class UrgenciasListView(ListView):
    model = Urgencias
    template_name = 'urgencias_list.html'
    
    

class UrgenciasDetailView(DetailView):
    model = Urgencias


@method_decorator(staff_member_required, name='dispatch')
class UrgenciasCreate(CreateView):
    model = Urgencias
    form_class = UrgenciasForm
    success_url = reverse_lazy('consultorio:pacientes_urgencias')



@method_decorator(staff_member_required, name='dispatch')
class UrgenciasUpdate(UpdateView):
    model = Urgencias
    form_class = UrgenciasForm
    template_name_suffix = '_update_form'

    
    def get_success_url(self):
        return reverse_lazy('consultorio:actualizar_urgencia', args=[self.object.id]) + '?ok'


@method_decorator(staff_member_required, name='dispatch')
class UrgenciasDeleteView(DeleteView):
    model = Urgencias
    success_url = reverse_lazy('consultorio:pacientes_urgencias')

aeskvlapivs/consultorio/templates/consultorio/includes/historia_clinica.html
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link href="{% static 'consultorio/css/custom_ckeditor.css' %}" rel="stylesheet">

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Historia Clínica</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'consultorio:actualizar_paciente' paciente.id  %}"><i>Editar</i></a>
        </li>
       
      </ul>
    </div>
  </div>
</nav>
{% endif %}

aeskvlapivs/consultorio/templates/consultorio/includes/reevaluacion_menu.html
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link href="{% static 'consultorio/css/custom_ckeditor.css' %}" rel="stylesheet">

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Abordaje General</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item" >
          <a class="nav-link" href="{% url 'consultorio:nueva_reevaluacion' %}"><i>Nueva Reevaluación</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}

aeskvlapivs/consultorio/templates/consultorio/includes/top_menu.html
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link href="{% static 'consultorio/css/custom_ckeditor.css' %}" rel="stylesheet">

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Abordaje General / Historia Clínica</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'consultorio:nuevo_paciente' %}"><i>Nuevo Paciente</i></a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" href="{% url 'consultorio:reevaluaciones' %}"><i>Reevaluaciones</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}

aeskvlapivs/consultorio/templates/consultorio/includes/urgencias_menu.html
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link href="{% static 'consultorio/css/custom_ckeditor.css' %}" rel="stylesheet">

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Urgencias</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item" >
          <a class="nav-link" href="{% url 'consultorio:nueva_urgencia' %}"><i>Nuevo Paciente de Urgencias /Evaluación Primaria</i></a>
          <a class="nav-link" href=""><i>Evaluciones Secundarias y Subsecuentes </i></a>
        </li>

        <li class="nav-item" >
          
        </li>


      </ul>
    </div>
  </div>
</nav>
{% endif %}